; V_JP SLPS_251.05
; V_NA SLUS_203.70
; V_FM SLPS_251.98
; KHVER = V_JP

; define FIX_SORA_LIPS

; NO_SLEEP makes skips really fast, but breaks things.
; define NO_SLEEP

; Early frame swap before VSYNC. 
; Reduces input delay on some emulators.
; Real console gets screen tearing and video glitches
; define REDUCE_LATENCY

define SKIP_SOUND

DefaultAutoSkip = 0
DefaultButtonCommands = 1
SectionBaseText = 0xff000

